CalendarPipe.ts, TimeAgoPipe.ts
Cleanup was not being performed because the name of the method is `ngOnDestroy` instead of `onDestroy`.
=> fix(*): wrong method name for cleanup

FromUnixPipe.spec.ts, FromUnixPipe.ts, README.md, package.json
Add from unix pipe to support parse unix timestamp: number or string
#15
=> feat(FromUnixPipe):Add unix pipe to parse unix timestamp to moment

README.md
Syntax was switched around and led users to https://github.com/urish/angular2-moment/blob/master/typings instead.
=> Fix link format for typings

CalendarPipe.ts, DateFormatPipe.spec.ts, DateFormatPipe.ts, DurationPipe.spec.ts, DurationPipe.ts, FromUnixPipe.ts, TimeAgoPipe.ts, package.json
angular2-beta.16 has changed pipes. The arguments array is now varargs.
EDIT: Looks like beta.16 requires another version of Zone.js
EDIT2: Updated zone.js and tests are passing
=> Update to beta.16

CalendarPipe.ts
When using angular2-moment 0.6.0 in my own project. Following error popped-up every time I start my webpack dev server:
```
webpack: bundle is now VALID.
[default] Checking started in a separate process...
[default] /Users/tang/Git Repositories/issue-webapp/node_modules/angular2-moment/CalendarPipe.ts:49:7 
Type 'EventEmitter<{}>' is not assignable to type 'EventEmitter<Date>'.
Type '{}' is not assignable to type 'Date'.
Property 'toDateString' is missing in type '{}'.
```
This patch fix this issue.
However, I cannot reproduce this issue in angular2-moment project directly. I tried to downgrade typescript related dependencies, modifying the tsconfig.json and tslint.json, etc.
Maybe this issue is related to #25.
=> Fixed generic type to prevent possible inferencing issue.

README.md, src/DifferencePipe.spec.ts, src/DifferencePipe.ts, src/index.ts
I need difference on one of my Projects, so i make a PR with this feature.
Take a look, and tell me if it is ok.
=> feat(difference): add amDifference pipe

package.json
Proposal to fix #76, as *.d.ts probably do not need linting
=> Exclude automated *.d.ts files from linting

src/index.ts
RollupJS ( A somewhat popular module bundler, now used by Ionic 2 ) requires all exports to be explicit, then it will try to optimise what's actually included in the bundle.
Sadly it can't handle "export * from".
Should solve issue #81
=> Explicitly provide the names of exported items rather than export *.

src/CalendarPipe.ts, src/TimeAgoPipe.ts
Added support for server side pre-rendering by checking for the existence of window and not setting any timeouts if its not available, which doesn't make sense for server-side pre-rendering anyway.
Fixes #82
=> Server side prerender

src/CalendarPipe.spec.ts, src/CalendarPipe.ts, src/TimeAgoPipe.spec.ts, src/TimeAgoPipe.ts
The updates are done outside the Angular zone, so Angular can't tell it the pipe needs to be updated. Fix by calling `markForCheck()` inside the NgZone.
=> fix(calender, timeAgo): automatic update broken

src/time-ago.pipe.spec.ts, src/time-ago.pipe.ts
=> “Expression has changed after it was checked” #84

.gitignore, README.md, package.json, src/index.ts, src/moment.module.ts, src/utc.pipe.spec.ts, src/utc.pipe.ts, tsconfig.json
Brings back the functionality of amUtc from angular-moment
=> Add UtcPipe to enable UTC mode in pipe chain.

src/calendar.pipe.ts
- wrap setTimeout with outsideAngularApp
- make initTimer to be not static anymore
#132
=> Calendar pipe: wrap setTimeout with outsideAngularApp

.gitignore, README.md, package.json, src/index.ts, src/moment.module.ts, src/parse.pipe.spec.ts, src/parse.pipe.ts, tsconfig.json
Added `ParsePipe` to give the same functionality of `amParse` filter from from angular-moment.
=> Add ParsePipe to enable parsing of custom-formatted date string

package.json
The compiled version, which is pushed to npm, contains a bundled version of `moment`, which makes it impossible to set the local from outside with 
```
import * as moment  from 'moment';
moment.locale('de');
```
because the internal `moment` version is not identical with the version you import from else where (see https://github.com/urish/angular2-moment/issues/149).
To fix that problem I remove the `node_modules` folder from the compiled version. A little disadvantage is that you have to specify `moment` in you project `package.json` as `dependencies` which means probably an breaking change.
=> Remove node_modules from compiled version

src/time-ago.pipe.spec.ts, src/time-ago.pipe.ts
`TimeAgoPipe` updates it's _output_ only when it detects it's _input_ has changed.
To do so, it does extract and compare a timestamp (milliseconds).
The output, however, depends not only on milliseconds, but also on locale. That was not taken into account.
I hereby propose a pull request that fixes this. 
Locale setting for current _moment_ instance is now considered. If you change locale globally (`moment.locale(...)`) you will need to make sure new _moment_ instance will trigger the pipe. I consider this the most predictable behaviour.
Please let me know your view, or suggest further changes. Thank you!
Resolves #172.
=> amTimeAgo pipe updates it's output when locale changes

README.md
When I used the amLocale pipe, I was struggeling with getting the locale loaded. When I did something like
```
{{ myMoment | amLocale:'de' | amDateFormat:'MMMM' }}
```
to show the month of a date, I always got the english name of the month. After searching the issues, I found https://github.com/urish/ngx-moment/issues/149#issuecomment-315011495, what finally helped me. I checked my node_modules that moment was installed and just did the import. I didn't test in my project, if the manual installation of moment.js is necesssary on a clean project.
I think, it would improve the documentation, if this note is added.
=> Improve documentation for locale import.

README.md, src/index.ts, src/moment.module.ts, src/parse-zone.pipe.spec.ts, src/parse-zone.pipe.ts
Hello!
With this pipe you can parse a string into a moment object preserving the original UTC offset. Its addition was suggested in [issue#39](https://github.com/urish/ngx-moment/issues/39) and can be handy.
=> Add `amParseZone` pipe

angular.json, package.json, src/time-ago.pipe.spec.ts, src/time-ago.pipe.ts, tsconfig.lint.json, tsconfig.spec.json
Makes it possible to use `TimeAgoPipe` with string/number dates when the `fullTemplateTypeCheck` Angular compiler option is enabled. Fixes #204.
Also enables type checking when running tests. Previously a test could contain a type error, but all tests would be reported as passing since ts-jest only uses TypeScript as a file preprocessor (see kulshekhar/ts-jest#79).
This is a non-breaking change which can be included in a minor/patch release.
=> Allow using all supported Moment inputs with TimeAgoPipe

.gitignore, README.md, src/duration.pipe.spec.ts, src/duration.pipe.ts, src/index.ts, src/moment-options.ts, src/moment.module.ts
Add ability to provide options to the moment module using the `forRoot` convention to supply options globally or per pipe
=> issue #202 ability to provide options to the MomentModule

src/time-ago.pipe.spec.ts, src/time-ago.pipe.ts
With this PR, the text of the amTimeAgo Pipe is updated when using plain Date-Values and changing the global locale (via e.g. "moment.locale('de')")
=> TimeAgoPipe: Improved Text Update on locale change when not using MomentInput

README.md, src/from-utc.pipe.spec.ts, src/from-utc.pipe.ts, src/parse.pipe.spec.ts, src/parse.pipe.ts
As per issue https://github.com/urish/ngx-moment/issues/186
=> feat: add format|formats to from-utc pipe and parse-pipe

src/locale.pipe.ts
It turns out that during AOT builds of NG apps there are issues when Date type is being passed to the pipe. While Momentjs accepts Date in it's constructor
=> Date type for amLocale pipe

src/add.pipe.spec.ts, src/add.pipe.ts, src/calendar.pipe.spec.ts, src/calendar.pipe.ts, src/date-format.pipe.spec.ts, src/date-format.pipe.ts, src/difference.pipe.ts, src/duration.pipe.ts, src/from-unix.pipe.spec.ts, src/from-unix.pipe.ts, src/from-utc.pipe.spec.ts, src/from-utc.pipe.ts, src/is-after.pipe.ts, src/is-before.pipe.ts, src/local.pipe.spec.ts, src/local.pipe.ts, src/locale.pipe.spec.ts, src/locale.pipe.ts, src/parse-zone.pipe.spec.ts, src/parse-zone.pipe.ts, src/parse.pipe.spec.ts, src/parse.pipe.ts, src/subtract.pipe.spec.ts, src/subtract.pipe.ts, src/time-ago.pipe.spec.ts, src/time-ago.pipe.ts, src/utc.pipe.spec.ts, src/utc.pipe.ts, tsconfig.json
=> fix: moment import reworked from wildcard to default
